version: '3.8'

services:
  env:
    build: .
    # cuda用のsetting
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      # TODO sshは上書きされないようにコンテナ内ではread onlyにしたい
      # modeを使えばできそうだけどうまくいかなかったので保留
      - type: bind
        source: ./
        target: /home/user/work/
      - type: bind
        source: ~/.ssh/
        target: /home/user/.ssh/
      - type: bind
        source: ~/.kaggle/
        target: /home/user/.kaggle/
    ports:
      - 7777:7777
    tty: true
    stdin_open: True 
    hostname: kuzira