#ref: https://github.com/phalanx-hk/kaggle_pipeline/blob/d621d8f76289fecd1cae379ac5aac3f5d58f099d/ruff.toml

target-version = "py310"
line-length = 120
indent-width = 4
output-format = "grouped"

[lint]
select = [
	"AIR",   # Airflow
	"ASYNC", # flake8-async
	"BLE",   # flake8-blind-except
	"C4",    # flake8-comprehensions
	"C90",   # mccabe
	"DTZ",   # flake8-datetimez
	"E",     # pycodestyle
	"F",     # Pyflakes
	"FA",    # flake8-future-annotations
	"FLY",   # flynt
	"I",     # isort
	"ICN",   # flake8-import-conventions
	"INT",   # flake8-gettext
	"NPY",   # NumPy-specific rules
	"PL",    # Pylint
	"PYI",   # flake8-pyi
	"RSE",   # flake8-raise
	"RUF",   # Ruff-specific rules
	"S",     # flake8-bandit
	"SLOT",  # flake8-slots
	"T10",   # flake8-debugger
	"TID",   # flake8-tidy-imports
	"TRY",   # tryceratops
	"UP",    # pyupgrade
	"W",     # pycodestyle
	"YTT",   # flake8-2020
]
ignore = [
	"S101",   # allow assertion
	"TRY003", # allow long exception message
]

[lint.flake8-annotations]
mypy-init-return = true

[lint.pydocstyle]
convention = "google"

[lint.isort]
length-sort = true

[lint.mccabe]
max-complexity = 10

[lint.pep8-naming]
classmethod-decorators = [
	"classmethod",
	"pydantic.validator",
	"pydantic.root_validator",
	"pydantic.field_validator",
	"pydantic.model_validator",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
