# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${path.output_dir}/${hydra.job.name}/${exp_name}/${run_name}
  sweep:
    dir: ${path.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - path: local
  # - model: example

# exp
exp_name: dummy
run_name: fold${fold}
notes: ""
tags: []

# common
seed: 42
debug: false
phase: train

# cv
n_splits: 5
fold: 0
