name: lightgbm
params:
  boosting_type: gbdt
  objective : multiclass
  num_class: 10
  metric: multi_logloss
  colsample_bytree: 0.8
  max_depth: 5
  subsample: 0.8
  min_child_weight: 1
  seed: 42
  learning_rate: 0.05
  verbose: -1