name: lightgbm
params:
  boosting_type: gbdt
  objective : regression
  metric: rmse
  colsample_bytree: 0.8
  max_depth: 5
  subsample: 0.8
  min_child_weight: 1
  seed: 42
  learning_rate: 0.05
  saved_feature_importance_type: 1  # gain
  verbose: -1