name: xgboost
num_boost_round: 3000
params:
  booster: gbtree
  objective : None 
  eval_metric: None 
  colsample_bytree: 0.8
  max_depth: 5
  subsample: 0.8
  min_child_weight: 1
  seed: 42
  learning_rate: 0.05
  verbosity: 1