input_dir: /home/kuto/kaggle/kaggle-template/input/yukiCup2023Autumn-atmaCup_dataset/yukiCup 2023 Autumn x atmaCup
output_dir: /home/kuto/kaggle/kaggle-template/output
feature_dir: /home/kuto/kaggle/kaggle-template/output/feature_store
model_dir: /home/kuto/kaggle/kaggle-template/output/train
sub_dir: ./