
defaults:
  - _self_
  - model: lgb_multiclass.yaml  # configs/model/から選択 
  - cv: skfold.yaml  # configs/cv/から選択
  - callbacks: lightgbm.yaml
  - logger: wandb.yaml

exp:
  version: "000"
  comment: "
  hello world
  "

common:
  timestamp: ${now:%M%d-%H%M-%S}
  input_dir: /home/user/work/input/
  output_dir: /home/user/work/output/${exp.version}_${common.timestamp}/
  seed: 42
  debug: False
  target_col: rating

hydra:
  run:
    dir: ${common.output_dir}

features:
  - CountEncode
  - OrdinalEncode
  - Numerical
