
defaults:
  - _self_
  - model: lgb_multiclass  # configs/model/から選択 
  - cv: skfold  # configs/cv/から選択

common:
  version: "002"
  comment: "
  debug
  "
  timestamp: None
  input_dir: /home/user/work/input/
  output_dir: /home/user/work/output/${common.version}_${common.timestamp}/
  seed: 42
  debug: True
  target_col: rating

wandb:
  init:  
    project: debug
    entity: kuto5046
    group: ${common.version}
    tags:
      - baseline
      - lightgbm

